version: "3.7"

networks:
  ntnxtools:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  mongo.volumes.automate_nutanix:
    driver: local

# Front

services:
  reverseproxy:
    build:
      context: ./reverseproxy
      dockerfile: Dockerfile
    image: ntnxtools_reverseproxy
    container_name: ntnxtools_reverseproxy
    restart: unless-stopped
    depends_on:
      - web
      - api_foundation
      - api_eula
      - api_setup
    ports:
      - 80:80
    environment: &environment
      REVERSE_PROXY_PORT: 80
      WEB_HOST: web
      WEB_PORT: 80
      API_CLUSTER_STATUS_HOST: api_cluster_status
      API_CLUSTER_STATUS_PORT: 80
      API_FOUNDATION_HOST: api_foundation
      API_FOUNDATION_PORT: 80
      API_EULA_HOST: api_eula
      API_EULA_PORT: 80
      API_SETUP_HOST: api_setup
      API_SETUP_PORT: 80
      API_POWER_HOST: api_power
      API_POWER_PORT: 80
      API_BULK_HOST: api_bulk
      API_BULK_PORT: 80
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    networks:
      ntnxtools:
        ipv4_address: 172.29.1.1

  # Middle

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: ntnxtools_web
    container_name: ntnxtools_web
    restart: unless-stopped
    ports:
      - 8201:80
    volumes:
      - ./web/html:/usr/share/nginx/html
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.1

  api_foundation:
    build:
      context: ./
      dockerfile: ./foundation/Dockerfile.yml
    image: ntnxtools_foundation
    container_name: ntnxtools_foundation
    restart: unless-stopped
    ports:
      - 8202:80
    volumes:
      - ./foundation/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.2

  api_eula:
    build:
      context: ./
      dockerfile: ./eula/Dockerfile.yml
    image: ntnxtools_eula
    container_name: ntnxtools_eula
    restart: unless-stopped
    ports:
      - 8203:80
    volumes:
      - ./eula/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.3

  api_setup:
    build:
      context: ./
      dockerfile: ./setup/Dockerfile.yml
    image: ntnxtools_setup
    container_name: ntnxtools_setup
    restart: unless-stopped
    ports:
      - 8204:80
    volumes:
      - ./setup/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.4

  api_power:
    build:
      context: ./
      dockerfile: ./power/Dockerfile.yml
    image: ntnxtools_power
    container_name: ntnxtools_power
    restart: unless-stopped
    ports:
      - 8205:80
    volumes:
      - ./power/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.5

  api_bulk:
    build:
      context: ./
      dockerfile: ./bulkactions/Dockerfile.yml
    image: ntnxtools_bulk
    container_name: ntnxtools_bulk
    restart: unless-stopped
    ports:
      - 8206:80
    depends_on:
      - api_foundation
      - api_eula
      - api_setup
    volumes:
      - ./bulkactions/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.6

  api_cluster_status:
    build:
      context: ./
      dockerfile: ./cluster_status_server/Dockerfile.yml
    image: ntnxtools_cluster_server
    container_name: ntnxtools_cluster_server
    restart: unless-stopped
    ports:
      - 8207:80
    depends_on:
      - collector_cluster_status
    volumes:
      - ./cluster_status_server/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.7

  collector_cluster_status:
    build:
      context: ./
      dockerfile: ./cluster_status_collector/Dockerfile.yml
    image: ntnxtools_cluster_collector
    container_name: ntnxtools_cluster_collector
    restart: unless-stopped
    volumes:
      - ./cluster_status_collector/src:/src
      - ./pylib:/pylib:z
    environment: *environment
    networks:
      ntnxtools:
        ipv4_address: 172.29.2.8

  # back

  mongo:
    image: mongo:4.2.3
    container_name: ntnxtools_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo.volumes.automate_nutanix:/data/db
    networks:
      ntnxtools:
        ipv4_address: 172.29.3.1

  mongo_express:
    image: mongo-express
    container_name: ntnxtools_mongo_express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      ntnxtools:
        ipv4_address: 172.29.3.2
