From python:3.8-slim
RUN pip install paramiko requests pymongo
WORKDIR /src
ENV PYTHONPATH $PYTHONPATH:/pylib
COPY ./cluster_status_collector/src /src
COPY ./pylib /pylib
CMD ["python3", "-u", "main.py"]